[build]
  command = "yarn build"
  publish = "dist"

[dev]
  command = "yarn dev"
  port = 3000

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
